### ISSUE TITLE
Performance way worse than normal Chrome

### ISSUE THREAD

**Issue by leontepe** [auchenberg/vscode-browser-preview#139]
I am running a [basic WebGL example ](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Animating_objects_with_WebGL) and the performance and in the Browser Preview is _really slow_ compared to the performance in standalone Chrome. Is this issue known?

**Comment by auchenberg** [comment]
Browser Preview is using Chrome' screencasting API, so performance depend on the perf of that API. For now this is the only way to embed a Chrome instance inside VS Code, so that's what we work with.

So yes, it's sadly a known issue. See https://github.com/auchenberg/vscode-browser-preview/issues/21
