### ISSUE TITLE
Allow right-click in url bar

### ISSUE THREAD

**Issue by misolori** [auchenberg/vscode-browser-preview#6]
Would be great to be able to paste in a URL via right-click in the url bar

**Comment by auchenberg** [comment]
@misolori What context menu options would you expect?

**Comment by misolori** [comment]
Just the basics, like this:

<img width="162" alt="image" src="https://user-images.githubusercontent.com/35271042/51512838-d2d8ee00-1dbc-11e9-8dd6-716d440ec789.png">

**Comment by Arminkhodaei** [comment]
Hi,

I have to say that I'm developing this option and it would be ready to PR in some days... 😉
menu style till now:

![vscode-preview-browser-menu](https://user-images.githubusercontent.com/13152108/51783183-6c045d80-214b-11e9-908e-1068661470b6.png)

**Comment by auchenberg** [comment]
@Arminkhodaei Amazing!

**Comment by auchenberg** [comment]
Ideally this should be provided by VS Code. See open issue https://github.com/Microsoft/vscode/issues/54285

**Comment by Arminkhodaei** [comment]
> Ideally this should be provided by VS Code. See open issue [Microsoft/vscode#54285](https://github.com/Microsoft/vscode/issues/54285)

Thanks. I hadn't seen that fairly old issue! Let me look into the webview's structure more profoundly...
By the way, In my opinion, that could be sensible to use an internal context menu in the meantime, and do refactoring and replace it, if there would be another option available by vscode's webview.

**Comment by Arminkhodaei** [comment]
@auchenberg I have a fundamental problem with providing this option by vscode. Probably I'm facing a misunderstanding about vscode webview's capabilities. In my point of view, a webview is simply a HTML container (iframe like) inside a main viewport which is provided by vscode. So, there isn't any address bar since actually there is no access to the external contents. With this in mind, how they can add a feature to contribute to the address bar context menu?!
Probably in this issue (https://github.com/Microsoft/vscode/issues/54285) they are talking about the viewport context menu, not the address bar one.
